apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-deployment
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
        - image: redis:alpine
          name: redis-container
          resources:
            requests:
              cpu: 1
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
            - mountPath: /redis-master
              name: redis-config
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 500Mi

        - name: redis-config
          configMap:
            name: log-config
